[tool.commitizen]
changelog_file = "docs/CHANGELOG.md"
major_version_zero = true
name = "cz_conventional_commits"
tag_format = "$version"
update_changelog_on_bump = true
version = "0.1.8"
version_files = [
  "metadata.lua:version",
]
